name: Deploy

on:
  workflow_dispatch:
    inputs:
      evironment:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - prod
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              cd Train-Spotting &&
              sudo docker stop TrainSpotting-Frontend &&
              sudo docker rm TrainSpotting-Frontend &&
              sudo docker stop TrainSpotting-Backend &&
              sudo docker rm TrainSpotting-Backend &&
              sudo git pull &&
              cd frontend &&
              sudo docker build -t frontend . &&
              sudo docker run -d --net host --name TrainSpotting-Frontend --restart unless-stopped -tld frontend &&
              cd ../backend &&
              /opt/apache-maven-3.9.3/bin/mvn clean package &&
              sudo docker build -t backend . &&
              sudo docker run -d --net host --name TrainSpotting-Backend --restart unless-stopped -tld backend
              '
